/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;
import modelo.Cuenta;
import view.CuentaView;
import controller.CuentaController;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author The Ice
 */
public class Inicio extends javax.swing.JFrame {

    
/*ImageIcon icono = new
ImageIcon(getClass().getResource("/imagenes/logo1.png"));
jLabel1.setIcon(icono);*/
    
  public static  CuentaView vistacuenta = new CuentaView();
  public static Cuenta modelocuenta = new Cuenta() {
      @Override
      public boolean depositar(double cantidad) {
          throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
      }

      @Override
      public boolean retirar(double cantidadRetirar) {
          throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
      }

      @Override
      public double consultar() {
          throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
      }
  };
  public static  CuentaController controladorcuenta = new CuentaController(modelocuenta, vistacuenta);
    
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtoncuenta = new javax.swing.JButton();
        jButtonsalir = new javax.swing.JButton();
        jButtontransacciones = new javax.swing.JButton();
        prestamo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButtonprestamo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtoncuenta.setBackground(new java.awt.Color(153, 153, 255));
        jButtoncuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtoncuenta.setText("Crear Cuenta");
        jButtoncuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncuentaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 130, 60));

        jButtonsalir.setBackground(new java.awt.Color(153, 153, 255));
        jButtonsalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonsalir.setText("Salir");
        jButtonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 90, -1));

        jButtontransacciones.setBackground(new java.awt.Color(153, 153, 255));
        jButtontransacciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtontransacciones.setText("Transacciones");
        jButtontransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontransaccionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtontransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 130, 60));

        prestamo.setBackground(new java.awt.Color(153, 153, 255));
        prestamo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prestamo.setText("Pago de Prestamo");
        prestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamoActionPerformed(evt);
            }
        });
        getContentPane().add(prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 170, 60));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Consulta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 130, 60));
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jButtonprestamo.setBackground(new java.awt.Color(153, 153, 255));
        jButtonprestamo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonprestamo.setText("Prestamo");
        jButtonprestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonprestamoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonprestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 130, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncuentaActionPerformed
        CrearCuenta inicio= new CrearCuenta();
        inicio.setVisible(true);
        this.setVisible(false);
        
        // En esta parte del codigo es para desplegar la ventana de crear cuenta.
    }//GEN-LAST:event_jButtoncuentaActionPerformed

    private void jButtontransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontransaccionesActionPerformed
        Transacciones inicio5= new Transacciones();
        inicio5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtontransaccionesActionPerformed

    private void prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamoActionPerformed
        PrestamoGUI inicio2= new PrestamoGUI();
        inicio2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_prestamoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Consulta inicio3= new Consulta();
       inicio3.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonsalirActionPerformed

    private void jButtonprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonprestamoActionPerformed
        // TODO add your handling code here:
         PagarPrestamo inicioj= new PagarPrestamo();
        inicioj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonprestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtoncuenta;
    private javax.swing.JButton jButtonprestamo;
    private javax.swing.JButton jButtonsalir;
    private javax.swing.JButton jButtontransacciones;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton prestamo;
    // End of variables declaration//GEN-END:variables
}
